# =============================================================================
# C O P Y R I G H T
# -----------------------------------------------------------------------------
# Copyright (c) 2019-2020 by Helmut Konrad Fahrendholz. All rights reserved.
# This file is property of Helmut Konrad Fahrendholz. Any unauthorized copy,
# use or distribution is an offensive act against international law and may
# be prosecuted under federal law. Its content is company confidential.
# =============================================================================
"""Extract images out of a PDF-Page

There are 2 types of images to extract:

    One the one hand, there is the image which stored in internal format
    One the other hand, there is the image that is generated by a color table

Furthermore there are some images which are composed out of other
images. Sometimes one Image is splitted into two or three parts. The
maximum of this split is one image per pixel line.

NOTE Currently this feature is experimental.
"""

import array
import collections
import io
import itertools
import os
import typing

import pdfminer.converter
import pdfminer.image
import pdfminer.layout
import pdfminer.pdfdocument
import pdfminer.pdfinterp
import pdfminer.pdftypes
import pdfminer.psparser
import PIL.Image
import PIL.ImageDraw
import PIL.ImageDraw2
import utila

import rawmaker.miner.converter


def extract_images(
        document: pdfminer.pdfdocument.PDFDocument,
        outputfolder,
        pages: tuple = None,
) -> dict:
    """Extract all images of `document` of selected `pages`.

    Hint: `Outputfolder` is only created if `document` contains some images.

    Args:
        document: source to extract images from
        outputfolder(str): write extracted images to
        pages(tuple): selective list to process pages
    Returns:
        dict with one list per page with containing images of this page
    """
    # ensure that page computation works correct
    if pages:
        pages = sorted(pages)

    collect = CollectAndMerge(outputfolder)

    # Processing layout
    content = pdfminer.pdfpage.PDFPage.create_pages(document)

    interpreter = create_fastimageextractor(collect.imagereciver)

    with utila.SkipCollector(pages) as collector:
        for number, page in enumerate(content):
            if collector.skip(number):
                continue
            page.pageid = number
            interpreter.process_page(page)

    result = collect.merge_and_write(document)
    return result


ExtractedImage = collections.namedtuple('ExtractedImage', 'image, name')


class CollectAndMerge:

    def __init__(self, outputfolder):
        self.outputfolder = outputfolder
        self.to_merge = collections.defaultdict(list)
        self.written = collections.defaultdict(list)

        self.writer = pdfminer.image.ImageWriter(outputfolder)

    def imagereciver(self, page, image):
        self.to_merge[page].append(image)

    def merge_and_write(self, document) -> dict:
        if not self.to_merge:
            # no images given
            return {}
        os.makedirs(self.outputfolder, exist_ok=True)
        # write merged images
        merged = merge_document_images(self.to_merge, document)
        for page, values in merged.items():
            for index, (image, ext) in enumerate(values):
                filename = f'{page}_{index}.{ext}'
                if isinstance(image, PIL.Image.Image):
                    outpath = os.path.join(self.outputfolder, filename)
                    with open(outpath, mode='wb') as output:
                        ext = ext.replace('jpg', 'jpeg')
                        image.save(output, format=ext)
                else:
                    image.name = f'{page}_{index}'
                    if image:
                        try:
                            self.writer.export_image(image)
                        except TypeError:
                            utila.error(f'empty export {image.name}')
                    else:
                        # TODO: CHECK WHY THIS CAN HAPPEN
                        utila.error(f'empty export {image.name}')
                self.written[page].append(ExtractedImage(image, filename))
        self.to_merge.clear()
        # convert defaultdict to normal dict, remove empty pages
        return {key: value for key, value in self.written.items() if value}


def merge_document_images(items, document):
    result = collections.defaultdict(list)
    # merge pages by yposition
    for page, content in items.items():
        merged = merge_page(content, document, page)
        result[page].extend(merged)
    return result


class ImageConverter(rawmaker.miner.converter.FlippedLayoutAnalyzer):

    def __init__(
            self,
            rsrcmgr,
            imagewriter,
    ):
        super().__init__(rsrcmgr=rsrcmgr)
        assert imagewriter is not None
        self.imagewriter = imagewriter
        # todo avoid duplicated parsed, TODO: check if we require this?
        self.parsed = set()

    def receive_layout(self, ltpage):
        super().receive_layout(ltpage)
        for item in ltpage:
            self.render_pagecontent(ltpage.pageid, item)

    def render_pagecontent(self, pageid, item):
        """Collect all imageable items"""
        if isinstance(item, pdfminer.layout.LTImage):
            self.render_result_image(item, pageid=pageid)
        elif isinstance(item, pdfminer.layout.LTFigure):
            self.render_figure(item, pageid=pageid)

    def render_result_image(
            self,
            image: pdfminer.layout.LTImage,
            pageid: int,
    ):
        if image.name in self.parsed:
            return
        self.parsed.add(image.name)
        self.imagewriter(pageid, image)

    def render_figure(
            self,
            item: pdfminer.layout.LTFigure,
            pageid: int,
    ):
        # TODO: RENDER CURVES ETC.
        images = item._objs  # pylint:disable=W0212
        images = [
            item for item in images if isinstance(item, pdfminer.layout.LTImage)
        ]
        if not images:
            return
        assert len(images) == 1, str(images)
        # TODO: Investigate with list
        image = images[0]  # pylint:disable=W0212
        self.render_result_image(image, pageid)


def merge_page(
        images: typing.List[pdfminer.layout.LTImage],
        document: callable,
        page: int,
):
    todo = [(
        utila.roundme(image.x0),
        utila.roundme(image.y0),
        utila.roundme(image.x1),
        utila.roundme(image.y1),
    ) for image in images]

    lookup = {str(item): line for item, line in zip(todo, images)}
    # assert len(lookup) == len(todo), f'{len(lookup)} != {len(todo)}'

    grouped = group_rectangles(todo)

    # convert back
    lines = [[lookup[str(item)] for item in group] for group in grouped]

    result = []
    try:
        result = [raw_images_merge(item, document) for item in lines]
    except ValueError:
        utila.error(f'could not parse images on page: {page}')

    return result


def group_rectangles(rectangles):
    """Split potential images by distance in y-coordiante."""
    grouped = itertools.groupby(rectangles, key=lambda x: x[0])
    result = []
    for _, group in grouped:
        ytopdown = sorted(group, key=lambda x: x[1])
        # split by distance
        splitted = [[ytopdown[0]]]
        for item in ytopdown[1:]:
            # maximal distance between two `pixel lines`
            vertical_distance = abs(item[1] - splitted[-1][-1][3])
            if vertical_distance < 5.0:
                splitted[-1].append(item)
            else:
                # start of new image
                splitted.append([item])
        result.extend(splitted)
    result = [item for item in result if len(item)]
    return result


BITMAP = '1'


def raw_images_merge(  # pylint:disable=R1260,R0914,too-many-branches,R0915
        images: typing.List[pdfminer.layout.LTImage],
        document,
) -> bytearray:
    """Merge list of images to one image."""
    image_height = sum(item.srcsize[1] for item in images)
    image_width = images[0].srcsize[0]
    size = (image_width, image_height)
    line_height = max(images[0].srcsize[1], 1)

    ext = extention(images[0])
    if ext != 'png':
        # TODO: png is not supported by pdfimage exporter properly
        if len(images) == 1:
            # no merge required
            return images[0], ext

    mode = 'RGB'
    result = PIL.Image.new(mode, size, color=0)
    renderer = PIL.ImageDraw.Draw(result, mode=mode)

    for ypos, image in enumerate(images):
        ext = extention(image)
        mode = 'RGB'
        size = image.srcsize
        bits = image.bits
        data = image.stream.get_data()
        colorspace = image.colorspace[0]
        if isinstance(colorspace, pdfminer.pdftypes.PDFObjRef):
            colorspace = document.getobj(colorspace.objid)
        elif isinstance(colorspace, list):
            colorspace = colorspace[0]
        # test list again!
        if isinstance(colorspace, list):
            # DEVICERGB
            if len(colorspace) == 2:
                if isinstance(colorspace[1], pdfminer.pdftypes.PDFObjRef):
                    colorspace = colorspace[1].resolve()
                else:
                    colorspace = colorspace[1]
            else:
                if isinstance(colorspace[3], pdfminer.pdftypes.PDFObjRef):
                    colorspace = colorspace[3].resolve()
                else:
                    colorspace = colorspace[3]
            data = rgb256_decoder(data, colorspace, bits=bits)
        elif colorspace:
            colorspace = colorspace.name
        else:
            # black and white
            mode = BITMAP

        if bits == 4:
            # TODO Do not know why this is required
            size = (size[0] + 1, size[1])
            mode = 'RGB'
        if colorspace == 'DeviceRGB':
            try:
                # open jpg etc.
                buffer = io.BytesIO(data)
                current = PIL.Image.open(buffer)
            except IOError:
                current = PIL.Image.frombytes(mode, size, data)
        else:
            try:
                current = PIL.Image.frombytes(mode, size, data)
            except ValueError:
                utila.error('could not decode')
                utila.error(vars(image))
                continue

        # convert to bitmap
        current = current.convert(mode=BITMAP, colors=1024, palette='1')
        loaded = io.BytesIO(current.tobitmap())
        current = PIL.Image.open(loaded)
        # render to common image
        renderer.bitmap((0, ypos * line_height), bitmap=current)
    return result, ext


def rgb256_decoder(data, dataspace, bits=8):
    # RGB
    # TODO: FIX TABLE ERRORS
    table = []
    if isinstance(dataspace, pdfminer.pdftypes.PDFStream):
        dataspace = dataspace.get_data()
    for index in range(0, len(dataspace), 3):
        try:
            table.append([
                dataspace[index],
                dataspace[index + 1],
                dataspace[index + 2],
            ])
        except IndexError:
            utila.error('rgb256 decoder out of bounds')
    result = []
    for item in data:
        try:
            if bits == 4:
                lower = table[item & (15)]
                higher = table[item & (15 >> 4 - 1)]
                result.extend(lower)
                result.extend(higher)
            elif bits == 8:
                result.extend(table[item])
            else:
                raise ValueError(f'{bits} bits not supported')
        except IndexError:
            utila.error('rgb256 decoder out of bounds')
    data = array.array("B", result).tobytes()
    return data


def extention(image) -> str:
    decoder = {
        'DCTDecode': 'jpg',
        'JPXDecode': 'jp2',
        'CCITTFaxDecode': 'tiff',
        'Default': 'png',
        'FlateDecode': 'png',
    }
    try:
        imagefilter = image.stream['Filter'].name
    except KeyError:
        imagefilter = 'Default'
    ext = decoder[imagefilter]
    return ext


# def extention(image) -> str:
#     stream = image.stream
#     filters = stream.get_filters()
#     (width, height) = image.srcsize
#     if len(filters) == 1 and filters[0][0] in LITERALS_DCT_DECODE:
#         ext = 'jpg'
#     elif (image.bits == 1 or image.bits == 8 and
#           image.colorspace in (LITERAL_DEVICE_RGB, LITERAL_DEVICE_GRAY)):
#         ext = 'bmp'
#     else:
#         ext = 'png'
#     return ext


class FastImageInterpreter(pdfminer.pdfinterp.PDFPageInterpreter):
    """Experimental, think about the sence of this ?optimization?."""

    # TODO: SEE DOCSTRING

    def __init__(self, rsrcmgr, device):
        super().__init__(rsrcmgr, device)
        self.fast = {
            'CS': self.do_CS,
            'Do': self.do_Do,
            'EI': self.do_EI,
            'MP': self.do_MP,
            'Q': self.do_Q,
            'SC': self.do_SC,
            'SCN': self.do_SCN,
            'cm': self.do_cm,
            'cs': self.do_cs,
            'sc': self.do_sc,
            'scn': self.do_scn,
        }

    # pylint:disable=W0613,R0201
    def render_char(self, matrix, font, fontsize, scaling, rise, cid, ncs,
                    graphicstate):
        # assert 0
        return

    def render_string(self, textstate, seq, ncs, graphicstate):
        return

    def do_TJ(self, seq):
        return

    def execute(self, streams):  # pylint:disable=R1260
        try:
            parser = pdfminer.pdfinterp.PDFContentParser(streams)
        except pdfminer.psparser.PSEOF:
            # empty page
            return
        while 1:
            try:
                (_, obj) = parser.nextobject()
            except pdfminer.psparser.PSEOF:
                break
            if isinstance(obj, pdfminer.psparser.PSKeyword):
                name = pdfminer.psparser.keyword_name(obj)
                # print(name)
                try:
                    func = self.fast[name]
                except KeyError:
                    continue
                nargs = func.__code__.co_argcount - 1
                # nargs = six.get_function_code(func).co_argcount - 1
                if nargs:
                    args = self.pop(nargs)
                    if len(args) == nargs:
                        func(*args)
                else:
                    func()

            else:
                self.push(obj)


def create_fastimageextractor(imagelistener):
    rsrcmgr = pdfminer.pdfinterp.PDFResourceManager()
    device = ImageConverter(rsrcmgr, imagewriter=imagelistener)
    # interpreter = FastImageInterpreter(rsrcmgr, device)
    interpreter = pdfminer.pdfinterp.PDFPageInterpreter(rsrcmgr, device)
    return interpreter
